[pytest]
pythonpath = backend
testpaths = backend/tests
filterwarnings =
    ignore::DeprecationWarning:reportlab.*:
    ignore::DeprecationWarning:jose.*:
    ignore::DeprecationWarning:passlib.*:
    ignore:.*datetime.datetime.utcnow\(\) is deprecated.*:DeprecationWarning
